import { createProps } from "@zag-js/types"
import type { UserDefinedContext } from "./editable.types"

export const props = createProps<UserDefinedContext>()([
  "activationMode",
  "autoResize",
  "dir",
  "disabled",
  "finalFocusEl",
  "form",
  "getRootNode",
  "id",
  "ids",
  "invalid",
  "maxLength",
  "name",
  "onEdit",
  "onFocusOutside",
  "onInteractOutside",
  "onPointerDownOutside",
  "onValueChange",
  "onValueCommit",
  "onValueRevert",
  "placeholder",
  "readOnly",
  "selectOnFocus",
  "startWithEditView",
  "submitMode",
  "translations",
  "value",
])
