import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "../../../shared/src/style.css"
import Link from "next/link"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <div
          style={{
            position: "fixed",
            left: "24px",
            bottom: "24px",
            backgroundColor: "blue",
            padding: "20px",
          }}
        >
          <Link href="/" style={{ color: "white" }}>
            ⬅ Back to Home
          </Link>
        </div>
      </body>
    </html>
  )
}
