import { SidebarNavigation } from "@/components/sidebar"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "../../../shared/src/style.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <div
          style={{
            position: "fixed",
            left: "24px",
            bottom: "24px",
            // backgroundColor: "blue",
            padding: "20px",
          }}
        >
          <SidebarNavigation
            items={[
              {
                id: "components",
                name: "Components",
                items: [
                  {
                    id: "components:collapsible",
                    name: "Collapsible",
                    items: [
                      {
                        id: "components:collapsible:controlled",
                        name: "Collapsible",
                        href: "/collapsible/controlled",
                      },
                      {
                        id: "components:collapsible:uncontrolled",
                        name: "Uncontrolled",
                        href: "/collapsible/uncontrolled",
                      },
                    ],
                  },
                ],
              },
            ]}
          />
          {/* <Link href="/" style={{ color: "white" }}>
            ⬅ Back to Home
          </Link> */}
        </div>
      </body>
    </html>
  )
}
