import { createAnatomy } from "@zag-js/anatomy"

export const anatomy = createAnatomy("scheduler").parts(
  "root",
  "header",
  "headerTitle",
  "prevTrigger",
  "nextTrigger",
  "todayTrigger",
  "viewSelect",
  "viewItem",
  "columnHeaders",
  "columnHeader",
  "grid",
  "gridRow",
  "allDayRow",
  "allDayLabel",
  "timeSlot",
  "timeGutter",
  "dayColumn",
  "dayCell",
  "dayCellTrigger",
  "monthGrid",
  "weekRow",
  "weekdayHeaderRow",
  "weekdayHeaderCell",
  "event",
  "eventResizeHandle",
  "currentTimeIndicator",
  "moreEvents",
  "dragGhost",
  "dragOrigin",
  "slotHighlight",
  "hourLabel",
  "hourLine",
  "agendaGroup",
  "agendaGroupTitle",
)

export const parts = anatomy.build()
