export { anatomy } from "./slider.anatomy"
export { connect } from "./slider.connect"
export { dom as unstable__dom } from "./slider.dom"
export { machine } from "./slider.machine"
export type { UserDefinedContext as Context, MachineApi as Api } from "./slider.types"
