import Head from "next/head"
import { Geist, Geist_Mono } from "next/font/google"

import { GithubIcon } from "@/components/visualizer/controls/icons"
import { componentsMap } from "@/components/components-map"
import { ComponentAnatomyName, getComponent } from "@zag-js/anatomy-icons"
import Link from "next/link"
import { ColorMode } from "@/components/color-mode"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export default function Home() {
  return (
    <>
      <Head>
        <title>Zag JS Visualizer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="page-header">
          <h1>Zag Visualizer</h1>
          <p>Explore Zag&apos;s state machines through interactive graphs</p>
          <div className="toolbar">
            <ColorMode />
            <Link href="https://github.com/chakra-ui/zag" target="_blank">
              <GithubIcon />
            </Link>
          </div>
        </div>
        <div className="machine-list">
          {Object.entries(componentsMap).map(([key, { title }]) => {
            const Anatomy = getComponent(key as ComponentAnatomyName)
            return (
              <Link key={key} href={`/${key}`} className="machine-item">
                <span>
                  {title}

                  <Link
                    className="github-link"
                    href={`https://github.com/chakra-ui/zag/blob/main/packages/machines/${key}/src/${key}.machine.ts`}
                    target="_blank"
                  >
                    <GithubIcon />
                  </Link>
                </span>
                {Anatomy && <Anatomy accentColor="#6eeb6e" className="anatomy-icon" />}
              </Link>
            )
          })}
        </div>
      </main>
    </>
  )
}
