stateDiagram
    %% Initial State
    [*] --> Unknown

    %% Unknown State
    Unknown --> Closed: SETUP \n do/ setupDocument
    
    %% Open State
    Open: <b>Open</b>
    Open: entry / checkTitleExists
    Open: entry / checkDescriptionExists \n
    Open: exit / removeValue \n
    Open: ⏰ every_100ms / logResult
    Open --> Closed: CLOSE
    Open --> Closed: TRIGGER_CLICK
    
    %% Open After Transition
    Open --> after_100ms
    after_100ms: ⏰ After 100ms
    after_100ms: do / checkTitleExists
    after_100ms --> Closed
    
    state Fork_1 <<fork>>
    Fork_1: ▲
    Open --> Fork_1: UNDERLAY_CLICK
    Fork_1 --> Open: [cond_1]  \n do / setFocusedValue
    Fork_1 --> Closed: [cond_2]
    note right of Fork_1
        cond_1 = not(isTopMostDialog)
        cond_2 = and(isTopMostDialog, closeOnOutsideClick, isValidUnderlayClick)
    end note

    %% Closed State
    Closed: <b>Closed</b>
    Closed: entry / invokeOnClose
    Closed: entry / clearPointerdownNode
    Closed --> Open: OPEN
    Closed --> Open: TRIGGER_CLICK

