type RouteData = {
  path: `/${string}`
  label: string
}

export const routesData: RouteData[] = [
  { label: "Bottom Sheet", path: "/bottom-sheet" },
  { label: "Bottom Sheet (Snap Points)", path: "/bottom-sheet-snap-points" },
  { label: "Bottom Sheet (Active Snap Point)", path: "/bottom-sheet-default-active-snap-point" },
  { label: "Scroll Area", path: "/scroll-area" },
  { label: "Scroll Area (Nested)", path: "/scroll-area-nested" },
  { label: "Async List", path: "/async-list" },
  { label: "Password Input", path: "/password-input" },
  { label: "Listbox", path: "/listbox" },
  { label: "Listbox (Grid)", path: "/listbox-grid" },
  { label: "Navigation Menu", path: "/navigation-menu" },
  { label: "Navigation Menu (Viewport)", path: "/navigation-menu-viewport" },
  { label: "Navigation Menu (Nested)", path: "/navigation-menu-nested" },
  { label: "Toggle", path: "/toggle" },
  { label: "Angle Slider", path: "/angle-slider" },
  { label: "Steps", path: "/steps" },
  { label: "QR Code", path: "/qr-code" },

  { label: "Signature Pad", path: "/signature-pad" },
  { label: "Floating Panel", path: "/floating-panel" },
  { label: "Tour", path: "/tour" },
  { label: "Collapsible", path: "/collapsible" },
  { label: "Clipboard", path: "/clipboard" },
  { label: "Tree View", path: "/tree-view" },
  { label: "Progress", path: "/progress" },
  { label: "File Upload", path: "/file-upload" },
  { label: "Presence", path: "/presence" },
  { label: "Avatar", path: "/avatar" },
  { label: "Color Picker", path: "/color-picker" },
  { label: "Switch", path: "/switch" },
  { label: "Carousel", path: "/carousel" },
  { label: "Date Picker (Single)", path: "/date-picker" },
  { label: "Date Picker (Range)", path: "/date-picker-range" },
  { label: "Date Picker (Multi)", path: "/date-picker-multi" },
  { label: "Date Picker (Inline)", path: "/date-picker-inline" },
  { label: "Date Picker (Month + Range)", path: "/date-picker-month-range" },
  { label: "Date Picker (Year + Range)", path: "/date-picker-year-range" },
  { label: "Select", path: "/select" },
  { label: "Accordion", path: "/accordion" },
  { label: "Checkbox", path: "/checkbox" },
  { label: "Combobox", path: "/combobox" },
  { label: "Editable", path: "/editable" },
  { label: "Dialog", path: "/dialog" },
  { label: "Hover Card", path: "/hover-card" },
  { label: "Menu", path: "/menu" },
  { label: "Menu Nested", path: "/menu-nested" },
  { label: "Menu With options", path: "/menu-options" },
  { label: "Context Menu", path: "/context-menu" },
  { label: "Number Input", path: "/number-input" },
  { label: "Pagination", path: "/pagination" },
  { label: "Pin Input", path: "/pin-input" },
  { label: "Popper", path: "/popper" },
  { label: "Popover", path: "/popover" },
  { label: "Radio Group", path: "/radio-group" },
  { label: "Range Slider", path: "/range-slider" },
  { label: "Rating Group", path: "/rating-group" },
  { label: "Slider", path: "/slider" },
  { label: "Tabs", path: "/tabs" },
  { label: "Tags Input", path: "/tags-input" },
  { label: "Timer (CountDown)", path: "/timer-countdown" },
  { label: "Timer (StopWatch)", path: "/timer-stopwatch" },
  { label: "Toast (Stacked)", path: "/toast-stacked" },
  { label: "Toast (Overlap)", path: "/toast-overlap" },
  { label: "Toggle Group", path: "/toggle-group" },
  { label: "Tooltip", path: "/tooltip" },
  { label: "Segment Control", path: "/segment-control" },
  { label: "Splitter", path: "/splitter" },
  { label: "JSON Tree", path: "/json-tree" },
]
