export { deepMerge, mergeProps } from "@zag-js/core"
export type { ContextFrom, EventFrom, StateFrom } from "@zag-js/core"
export * from "./attach"
export * from "./normalize-props"
export * from "./use-machine"
