export { mergeProps, deepMerge } from "@zag-js/core"
export type { ContextFrom, EventFrom, StateFrom } from "@zag-js/core"
export * from "./use-machine"
export * from "./normalize-props"
export * from "./spread-rest"
