name: Visualize Logic

on:
  pull_request:
    types: [opened]
    paths:
      - .xstate/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16.x

      - name: Visualizer link
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            Visualize the logic of the machines [here](https://state-machine-viz.vercel.app/pr/${{ github.event.number }}) :confetti_ball:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
