import { VNode } from "preact"
import { lazy } from "preact-iso"

interface RouteDefinition {
  path: string
  component: () => VNode<any>
}

export const routes: RouteDefinition[] = [
  {
    path: "/",
    component: lazy(() => import("./pages/home")),
  },
  { path: "/cascade-select/basic", component: lazy(() => import("./pages/cascade-select/basic")) },
  { path: "/marquee/basic", component: lazy(() => import("./pages/marquee/basic")) },
  { path: "/image-cropper/basic", component: lazy(() => import("./pages/image-cropper/basic")) },
  { path: "/image-cropper/circle", component: lazy(() => import("./pages/image-cropper/circle")) },
  { path: "/image-cropper/fixed", component: lazy(() => import("./pages/image-cropper/fixed")) },
  { path: "/drawer/basic", component: lazy(() => import("./pages/drawer/basic")) },
  { path: "/drawer/snap-points", component: lazy(() => import("./pages/drawer/snap-points")) },
  { path: "/drawer/active-snap-point", component: lazy(() => import("./pages/drawer/active-snap-point")) },
  { path: "/drawer/indent-effect", component: lazy(() => import("./pages/drawer/indent-effect")) },
  { path: "/drawer/swipe-area", component: lazy(() => import("./pages/drawer/swipe-area")) },
  { path: "/drawer/cross-axis-scroll", component: lazy(() => import("./pages/drawer/cross-axis-scroll")) },
  { path: "/drawer/range-input", component: lazy(() => import("./pages/drawer/range-input")) },
  { path: "/drawer/action-sheet", component: lazy(() => import("./pages/drawer/action-sheet")) },
  { path: "/drawer/controlled", component: lazy(() => import("./pages/drawer/controlled")) },
  { path: "/drawer/mobile-nav", component: lazy(() => import("./pages/drawer/mobile-nav")) },
  { path: "/drawer/multiple-trigger", component: lazy(() => import("./pages/drawer/multiple-trigger")) },
  { path: "/drawer/nested", component: lazy(() => import("./pages/drawer/nested")) },
  { path: "/drawer/non-modal", component: lazy(() => import("./pages/drawer/non-modal")) },
  { path: "/scroll-area/basic", component: lazy(() => import("./pages/scroll-area/basic")) },
  { path: "/scroll-area/nested", component: lazy(() => import("./pages/scroll-area/nested")) },
  { path: "/scroll-area/column-reverse", component: lazy(() => import("./pages/scroll-area/column-reverse")) },
  { path: "/async-list/basic", component: lazy(() => import("./pages/async-list/basic")) },
  { path: "/password-input/basic", component: lazy(() => import("./pages/password-input/basic")) },
  { path: "/listbox/basic", component: lazy(() => import("./pages/listbox/basic")) },
  { path: "/listbox/grid", component: lazy(() => import("./pages/listbox/grid")) },
  { path: "/listbox/controlled-ignore", component: lazy(() => import("./pages/listbox/controlled-ignore")) },
  { path: "/listbox/external-value-change", component: lazy(() => import("./pages/listbox/external-value-change")) },
  { path: "/listbox/transfer", component: lazy(() => import("./pages/listbox/transfer")) },
  { path: "/listbox/search", component: lazy(() => import("./pages/listbox/search")) },
  { path: "/listbox/virtualized", component: lazy(() => import("./pages/listbox/virtualized")) },
  { path: "/navigation-menu/basic", component: lazy(() => import("./pages/navigation-menu/basic")) },
  { path: "/navigation-menu/viewport", component: lazy(() => import("./pages/navigation-menu/viewport")) },
  { path: "/toggle/basic", component: lazy(() => import("./pages/toggle/basic")) },
  { path: "/angle-slider/basic", component: lazy(() => import("./pages/angle-slider/basic")) },
  { path: "/steps/basic", component: lazy(() => import("./pages/steps/basic")) },
  { path: "/qr-code/basic", component: lazy(() => import("./pages/qr-code/basic")) },
  { path: "/qr-code/download", component: lazy(() => import("./pages/qr-code/download")) },
  { path: "/signature-pad/basic", component: lazy(() => import("./pages/signature-pad/basic")) },
  { path: "/floating-panel/basic", component: lazy(() => import("./pages/floating-panel/basic")) },
  { path: "/floating-panel/controlled", component: lazy(() => import("./pages/floating-panel/controlled")) },
  { path: "/floating-panel/focus-trap", component: lazy(() => import("./pages/floating-panel/focus-trap")) },
  { path: "/floating-panel/popover-inside", component: lazy(() => import("./pages/floating-panel/popover-inside")) },
  { path: "/tour/basic", component: lazy(() => import("./pages/tour/basic")) },
  { path: "/tour/wait-step", component: lazy(() => import("./pages/tour/wait-step")) },
  { path: "/tour/wait-for-input-event", component: lazy(() => import("./pages/tour/wait-for-input-event")) },
  { path: "/tour/step-types", component: lazy(() => import("./pages/tour/step-types")) },
  { path: "/tour/conditional", component: lazy(() => import("./pages/tour/conditional")) },
  { path: "/collapsible/basic", component: lazy(() => import("./pages/collapsible/basic")) },
  { path: "/collapsible/nested", component: lazy(() => import("./pages/collapsible/nested")) },
  { path: "/clipboard/basic", component: lazy(() => import("./pages/clipboard/basic")) },
  { path: "/tree-view/basic", component: lazy(() => import("./pages/tree-view/basic")) },
  { path: "/tree-view/async", component: lazy(() => import("./pages/tree-view/async")) },
  { path: "/tree-view/checkbox", component: lazy(() => import("./pages/tree-view/checkbox")) },
  { path: "/tree-view/rename", component: lazy(() => import("./pages/tree-view/rename")) },
  { path: "/tree-view/filtering", component: lazy(() => import("./pages/tree-view/filtering")) },
  { path: "/tree-view/links", component: lazy(() => import("./pages/tree-view/links")) },
  { path: "/tree-view/in-dialog", component: lazy(() => import("./pages/tree-view/in-dialog")) },
  { path: "/progress/basic", component: lazy(() => import("./pages/progress/basic")) },
  { path: "/file-upload/basic", component: lazy(() => import("./pages/file-upload/basic")) },
  { path: "/file-upload/with-rejections", component: lazy(() => import("./pages/file-upload/with-rejections")) },
  { path: "/file-upload/cover", component: lazy(() => import("./pages/file-upload/cover")) },
  { path: "/file-upload/react-hook-form", component: lazy(() => import("./pages/file-upload/react-hook-form")) },
  { path: "/file-upload/transform", component: lazy(() => import("./pages/file-upload/transform")) },
  { path: "/presence/basic", component: lazy(() => import("./pages/presence/basic")) },
  { path: "/avatar/basic", component: lazy(() => import("./pages/avatar/basic")) },
  { path: "/color-picker/basic", component: lazy(() => import("./pages/color-picker/basic")) },
  { path: "/color-picker/inline", component: lazy(() => import("./pages/color-picker/inline")) },
  { path: "/color-picker/in-dialog", component: lazy(() => import("./pages/color-picker/in-dialog")) },
  { path: "/switch/basic", component: lazy(() => import("./pages/switch/basic")) },
  { path: "/carousel/basic", component: lazy(() => import("./pages/carousel/basic")) },
  { path: "/carousel/thumbnail", component: lazy(() => import("./pages/carousel/thumbnail")) },
  { path: "/carousel/dialog", component: lazy(() => import("./pages/carousel/dialog")) },
  { path: "/date-picker/basic", component: lazy(() => import("./pages/date-picker/basic")) },
  { path: "/date-picker/range", component: lazy(() => import("./pages/date-picker/range")) },
  { path: "/date-picker/range-calendar", component: lazy(() => import("./pages/date-picker/range-calendar")) },
  { path: "/date-picker/multi", component: lazy(() => import("./pages/date-picker/multi")) },
  { path: "/date-picker/inline", component: lazy(() => import("./pages/date-picker/inline")) },
  { path: "/date-picker/month-range", component: lazy(() => import("./pages/date-picker/month-range")) },
  { path: "/date-picker/year-range", component: lazy(() => import("./pages/date-picker/year-range")) },
  { path: "/date-picker/custom-calendar", component: lazy(() => import("./pages/date-picker/custom-calendar")) },
  { path: "/date-picker/date-time", component: lazy(() => import("./pages/date-picker/date-time")) },
  {
    path: "/date-picker/date-input-date-picker",
    component: lazy(() => import("./pages/date-picker/date-input-date-picker")),
  },
  { path: "/date-picker/month", component: lazy(() => import("./pages/date-picker/month")) },
  { path: "/date-picker/year", component: lazy(() => import("./pages/date-picker/year")) },
  { path: "/date-picker/format-parse", component: lazy(() => import("./pages/date-picker/format-parse")) },
  {
    path: "/date-picker/composition-min-max",
    component: lazy(() => import("./pages/date-picker/composition-min-max")),
  },
  { path: "/date-picker/multiple-months", component: lazy(() => import("./pages/date-picker/multiple-months")) },
  { path: "/date-picker/composition-inline", component: lazy(() => import("./pages/date-picker/composition-inline")) },
  { path: "/date-picker/week-numbers", component: lazy(() => import("./pages/date-picker/week-numbers")) },
  { path: "/date-picker/dynamic-max", component: lazy(() => import("./pages/date-picker/dynamic-max")) },
  { path: "/date-picker/unavailable", component: lazy(() => import("./pages/date-picker/unavailable")) },
  { path: "/date-input/basic", component: lazy(() => import("./pages/date-input/basic")) },
  { path: "/date-input/controlled", component: lazy(() => import("./pages/date-input/controlled")) },
  { path: "/date-input/time-only", component: lazy(() => import("./pages/date-input/time-only")) },
  {
    path: "/date-input/time-only-controlled",
    component: lazy(() => import("./pages/date-input/time-only-controlled")),
  },
  { path: "/date-input/timezone", component: lazy(() => import("./pages/date-input/timezone")) },
  { path: "/date-input/hour-cycle", component: lazy(() => import("./pages/date-input/hour-cycle")) },
  { path: "/date-input/min-max", component: lazy(() => import("./pages/date-input/min-max")) },
  { path: "/date-input/range", component: lazy(() => import("./pages/date-input/range")) },
  { path: "/date-input/custom-calendar", component: lazy(() => import("./pages/date-input/custom-calendar")) },
  { path: "/select/basic", component: lazy(() => import("./pages/select/basic")) },
  { path: "/select/controlled-ignore", component: lazy(() => import("./pages/select/controlled-ignore")) },
  { path: "/select/external-value-change", component: lazy(() => import("./pages/select/external-value-change")) },
  { path: "/select/async", component: lazy(() => import("./pages/select/async")) },
  { path: "/select/combobox", component: lazy(() => import("./pages/select/combobox")) },
  { path: "/select/in-dialog", component: lazy(() => import("./pages/select/in-dialog")) },
  { path: "/select/in-popover", component: lazy(() => import("./pages/select/in-popover")) },
  { path: "/select/multiple-controlled", component: lazy(() => import("./pages/select/multiple-controlled")) },
  { path: "/select/tabs", component: lazy(() => import("./pages/select/tabs")) },
  { path: "/select/virtualized", component: lazy(() => import("./pages/select/virtualized")) },
  { path: "/accordion/basic", component: lazy(() => import("./pages/accordion/basic")) },
  { path: "/checkbox/basic", component: lazy(() => import("./pages/checkbox/basic")) },
  { path: "/combobox/basic", component: lazy(() => import("./pages/combobox/basic")) },
  { path: "/combobox/async", component: lazy(() => import("./pages/combobox/async")) },
  { path: "/combobox/controlled-ignore", component: lazy(() => import("./pages/combobox/controlled-ignore")) },
  { path: "/combobox/external-value-change", component: lazy(() => import("./pages/combobox/external-value-change")) },
  { path: "/combobox/multiple", component: lazy(() => import("./pages/combobox/multiple")) },
  { path: "/combobox/cmdk", component: lazy(() => import("./pages/combobox/cmdk")) },
  { path: "/combobox/combo-tags", component: lazy(() => import("./pages/combobox/combo-tags")) },
  { path: "/combobox/combo-textarea", component: lazy(() => import("./pages/combobox/combo-textarea")) },
  { path: "/combobox/tabs", component: lazy(() => import("./pages/combobox/tabs")) },
  { path: "/combobox/custom-value", component: lazy(() => import("./pages/combobox/custom-value")) },
  { path: "/combobox/controlled-input", component: lazy(() => import("./pages/combobox/controlled-input")) },
  { path: "/combobox/rehydrate", component: lazy(() => import("./pages/combobox/rehydrate")) },
  { path: "/combobox/virtualized", component: lazy(() => import("./pages/combobox/virtualized")) },
  { path: "/combobox/emoji-picker", component: lazy(() => import("./pages/combobox/emoji-picker")) },
  { path: "/editable/basic", component: lazy(() => import("./pages/editable/basic")) },
  { path: "/editable/controlled", component: lazy(() => import("./pages/editable/controlled")) },
  { path: "/dialog/basic", component: lazy(() => import("./pages/dialog/basic")) },
  { path: "/dialog/cloudinary", component: lazy(() => import("./pages/dialog/cloudinary")) },
  { path: "/dialog/controlled", component: lazy(() => import("./pages/dialog/controlled")) },
  { path: "/dialog/datepicker", component: lazy(() => import("./pages/dialog/datepicker")) },
  { path: "/dialog/delayed-close", component: lazy(() => import("./pages/dialog/delayed-close")) },
  { path: "/dialog/multiple-trigger", component: lazy(() => import("./pages/dialog/multiple-trigger")) },
  {
    path: "/dialog/multiple-trigger-controlled",
    component: lazy(() => import("./pages/dialog/multiple-trigger-controlled")),
  },
  { path: "/dialog/popover-nested", component: lazy(() => import("./pages/dialog/popover-nested")) },
  { path: "/dialog/scroll-outside", component: lazy(() => import("./pages/dialog/scroll-outside")) },
  { path: "/hover-card/basic", component: lazy(() => import("./pages/hover-card/basic")) },
  { path: "/hover-card/hovercard-in-dialog", component: lazy(() => import("./pages/hover-card/hovercard-in-dialog")) },
  { path: "/hover-card/multiple-trigger", component: lazy(() => import("./pages/hover-card/multiple-trigger")) },
  { path: "/menu/basic", component: lazy(() => import("./pages/menu/basic")) },
  { path: "/menu/overflow", component: lazy(() => import("./pages/menu/overflow")) },
  { path: "/menu/nested", component: lazy(() => import("./pages/menu/nested")) },
  { path: "/menu/options", component: lazy(() => import("./pages/menu/options")) },
  { path: "/menu/combobox", component: lazy(() => import("./pages/menu/combobox")) },
  { path: "/menu/in-dialog", component: lazy(() => import("./pages/menu/in-dialog")) },
  { path: "/menu/lazy-mounted", component: lazy(() => import("./pages/menu/lazy-mounted")) },
  { path: "/menu/links", component: lazy(() => import("./pages/menu/links")) },
  { path: "/menu/multiple-controlled", component: lazy(() => import("./pages/menu/multiple-controlled")) },
  { path: "/menu/multiple-nested", component: lazy(() => import("./pages/menu/multiple-nested")) },
  { path: "/menu/multiple-trigger", component: lazy(() => import("./pages/menu/multiple-trigger")) },
  { path: "/context-menu/basic", component: lazy(() => import("./pages/context-menu/basic")) },
  { path: "/context-menu/multiple-trigger", component: lazy(() => import("./pages/context-menu/multiple-trigger")) },
  { path: "/number-input/basic", component: lazy(() => import("./pages/number-input/basic")) },
  { path: "/number-input/wrapped", component: lazy(() => import("./pages/number-input/wrapped")) },
  { path: "/pagination/basic", component: lazy(() => import("./pages/pagination/basic")) },
  { path: "/pin-input/basic", component: lazy(() => import("./pages/pin-input/basic")) },
  { path: "/pin-input/controlled", component: lazy(() => import("./pages/pin-input/controlled")) },
  { path: "/pin-input/transform-paste", component: lazy(() => import("./pages/pin-input/transform-paste")) },
  { path: "/popper/basic", component: lazy(() => import("./pages/popper/basic")) },
  { path: "/popover/basic", component: lazy(() => import("./pages/popover/basic")) },
  { path: "/popover/composition-controlled", component: lazy(() => import("./pages/popover/composition-controlled")) },
  { path: "/popover/in-dialog", component: lazy(() => import("./pages/popover/in-dialog")) },
  { path: "/popover/multiple-controlled", component: lazy(() => import("./pages/popover/multiple-controlled")) },
  { path: "/popover/multiple-trigger", component: lazy(() => import("./pages/popover/multiple-trigger")) },
  { path: "/popover/nested", component: lazy(() => import("./pages/popover/nested")) },
  { path: "/popover/selection", component: lazy(() => import("./pages/popover/selection")) },
  { path: "/popover/single-tab-stop", component: lazy(() => import("./pages/popover/single-tab-stop")) },
  { path: "/popover/responsive", component: lazy(() => import("./pages/popover/responsive")) },
  { path: "/popover/sibling-dialog", component: lazy(() => import("./pages/popover/sibling-dialog")) },
  { path: "/popover/tooltip", component: lazy(() => import("./pages/popover/tooltip")) },
  { path: "/radio-group/basic", component: lazy(() => import("./pages/radio-group/basic")) },
  { path: "/range-slider/basic", component: lazy(() => import("./pages/range-slider/basic")) },
  { path: "/rating-group/basic", component: lazy(() => import("./pages/rating-group/basic")) },
  { path: "/slider/basic", component: lazy(() => import("./pages/slider/basic")) },
  { path: "/slider/change-end", component: lazy(() => import("./pages/slider/change-end")) },
  { path: "/slider/number-input", component: lazy(() => import("./pages/slider/number-input")) },
  { path: "/slider/in-popover", component: lazy(() => import("./pages/slider/in-popover")) },
  { path: "/slider/tooltip", component: lazy(() => import("./pages/slider/tooltip")) },
  { path: "/tabs/basic", component: lazy(() => import("./pages/tabs/basic")) },
  { path: "/tabs/with-link", component: lazy(() => import("./pages/tabs/with-link")) },
  { path: "/tags-input/basic", component: lazy(() => import("./pages/tags-input/basic")) },
  { path: "/tags-input/validate", component: lazy(() => import("./pages/tags-input/validate")) },
  { path: "/tags-input/allow-duplicates", component: lazy(() => import("./pages/tags-input/allow-duplicates")) },
  { path: "/tags-input/sentence-builder", component: lazy(() => import("./pages/tags-input/sentence-builder")) },
  { path: "/timer/countdown", component: lazy(() => import("./pages/timer/countdown")) },
  { path: "/timer/stopwatch", component: lazy(() => import("./pages/timer/stopwatch")) },
  { path: "/toast/stacked", component: lazy(() => import("./pages/toast/stacked")) },
  { path: "/toast/overlap", component: lazy(() => import("./pages/toast/overlap")) },
  { path: "/toggle-group/basic", component: lazy(() => import("./pages/toggle-group/basic")) },
  { path: "/toc/basic", component: lazy(() => import("./pages/toc/basic")) },
  { path: "/toc/indicator", component: lazy(() => import("./pages/toc/indicator")) },
  { path: "/toc/scroll-element", component: lazy(() => import("./pages/toc/scroll-element")) },
  { path: "/tooltip/basic", component: lazy(() => import("./pages/tooltip/basic")) },
  { path: "/tooltip/dialog", component: lazy(() => import("./pages/tooltip/dialog")) },
  { path: "/tooltip/follow-cursor", component: lazy(() => import("./pages/tooltip/follow-cursor")) },
  { path: "/tooltip/multiple-trigger", component: lazy(() => import("./pages/tooltip/multiple-trigger")) },
  { path: "/segment-control/basic", component: lazy(() => import("./pages/segment-control/basic")) },
  { path: "/splitter/basic", component: lazy(() => import("./pages/splitter/basic")) },
  { path: "/splitter/collapsible", component: lazy(() => import("./pages/splitter/collapsible")) },
  { path: "/splitter/conditional", component: lazy(() => import("./pages/splitter/conditional")) },
  { path: "/splitter/controlled", component: lazy(() => import("./pages/splitter/controlled")) },
  { path: "/splitter/multiple", component: lazy(() => import("./pages/splitter/multiple")) },
  { path: "/splitter/nested", component: lazy(() => import("./pages/splitter/nested")) },
  { path: "/splitter/fixed-size", component: lazy(() => import("./pages/splitter/fixed-size")) },
  { path: "/splitter/group-resize-behavior", component: lazy(() => import("./pages/splitter/group-resize-behavior")) },
  { path: "/splitter/persistent-layout", component: lazy(() => import("./pages/splitter/persistent-layout")) },
  { path: "/splitter/pixel-constraints", component: lazy(() => import("./pages/splitter/pixel-constraints")) },
  { path: "/splitter/relative-units", component: lazy(() => import("./pages/splitter/relative-units")) },
  { path: "/json-tree/basic", component: lazy(() => import("./pages/json-tree/basic")) },
  { path: "/hotkeys/basic", component: lazy(() => import("./pages/hotkeys/basic")) },
  { path: "/hotkeys/sequences", component: lazy(() => import("./pages/hotkeys/sequences")) },
  { path: "/hotkeys/scopes", component: lazy(() => import("./pages/hotkeys/scopes")) },
  { path: "/hotkeys/command-dialog", component: lazy(() => import("./pages/hotkeys/command-dialog")) },
  { path: "/hotkeys/key-recorder", component: lazy(() => import("./pages/hotkeys/key-recorder")) },
  {
    path: "/:component",
    component: lazy(() => import("./pages/component")),
  },
]
